<?php 
use Illuminate\Support\Facades\Schema;

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;
//Generated By PlantUML Command
class CreateCuidadorespecialidads extends Migration{
	public function up(){ 
 		Schema::create('cuidadorespecialidads', function (Blueprint $table) { 
			$table->bigIncrements('id');
			$table->integer('cuidador_id');
			$table->integer('especialidad_id');
			$table->timestamps();
		});
 	} 
	public function down(){
 
	} 
}