<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

//Generated By PlantUML Command
class Animal extends Model
{
    protected $fillable = [
        'nombre',
        'Caracteristicas',
        'especie_id',
    ];

    public function animalrecintos()
    {
        return $this->hasMany('App\Models\AnimalRecinto', 'anima_id');
    }

    public function actividadanimals()
    {
        return $this->hasMany('App\Models\ActividadAnimal', 'anima_id');
    }

    public function animalcuidadors()
    {
        return $this->hasMany('App\Models\AnimalCuidador', 'anima_id');
    }

    public function especie()
    {
        return $this->belongsTo('App\Models\Especie', 'especie_id');
    }
}
