<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

//Generated By PlantUML Command
class Cuidador extends Model
{
    protected $fillable = [
        'nombre',
        'edad',
        'salario',
    ];

    public function animalcuidadors()
    {
        return $this->hasMany('App\Models\AnimalCuidador', 'cuidador_id');
    }

    public function cuidadorespecialidads()
    {
        return $this->hasMany('App\Models\CuidadorEspecialidad', 'cuidador_id');
    }
}
